version: "3.8"

services:

  influxdb:
    image: influxdb
    volumes:
      - ./data/influxdb-data:/var/lib/influxdb
    network_mode: "host"
    environment:
      - INFLUXDB_DB=M13

  grafana:
    image: grafana/grafana
    user: "0"
    volumes:
      - ./data/grafana-data:/var/lib/grafana
    network_mode: "host"
    ports:
      - 3000:3000
